const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema({
  year: { type: Number, required: true },
  month: { type: Number, required: true }, // 1-12
  generatedAt: { type: Date, default: Date.now },
  isAutoGenerated: { type: Boolean, default: false },
  summary: {
    totalIn: Number,
    totalOut: Number,
    netBalance: Number,
    uniqueSkus: Number,
    topModels: [{ skuName: String, totalIn: Number, totalOut: Number }],
  },
  // Full daily breakdown stored as JSON
  dailyData: { type: mongoose.Schema.Types.Mixed },
  shiftData: { type: mongoose.Schema.Types.Mixed },
}, { timestamps: true });

reportSchema.index({ year: 1, month: 1 });

module.exports = mongoose.model('Report', reportSchema);
