const Transaction = require('../models/Transaction');
const Report      = require('../models/Report');

async function generateMonthlyReport(year, month, isAuto = true) {
  const prefix = `${year}-${String(month).padStart(2, '0')}`;
  const txs = await Transaction.find({ txDate: { $regex: `^${prefix}` } }).lean();

  let totalIn = 0, totalOut = 0;
  const skuMap   = {};
  const dailyMap = {};

  txs.forEach(t => {
    const q = t.quantity;
    if (t.type === 'IN')  totalIn  += q;
    if (t.type === 'OUT') totalOut += q;

    if (!skuMap[t.skuName])   skuMap[t.skuName]   = { skuName: t.skuName, totalIn: 0, totalOut: 0 };
    if (!dailyMap[t.txDate]) dailyMap[t.txDate] = { in: 0, out: 0 };
    if (t.type === 'IN')  { skuMap[t.skuName].totalIn   += q; dailyMap[t.txDate].in  += q; }
    if (t.type === 'OUT') { skuMap[t.skuName].totalOut  += q; dailyMap[t.txDate].out += q; }
  });

  const topModels = Object.values(skuMap)
    .sort((a, b) => (b.totalIn + b.totalOut) - (a.totalIn + a.totalOut))
    .slice(0, 10);

  return Report.findOneAndUpdate(
    { year, month },
    {
      year, month, isAutoGenerated: isAuto, generatedAt: new Date(),
      summary: { totalIn, totalOut, netBalance: totalIn - totalOut, uniqueSkus: Object.keys(skuMap).length, topModels },
      dailyData: dailyMap,
      shiftData: {},
    },
    { upsert: true, new: true }
  );
}

module.exports = { generateMonthlyReport };
